In [1]:
import pandas as pd
import os
import sys
import numpy as np
import json
pd.set_option("display.max_columns", 100)

# IDs

#### Teams

In [2]:
from nba_api.stats.static import teams
nba_teams = teams.get_teams()
for team in nba_teams[:5]:
    print(f"{team['full_name']} ({team['abbreviation']}): {team['id']}")

Atlanta Hawks (ATL): 1610612737
Boston Celtics (BOS): 1610612738
Cleveland Cavaliers (CLE): 1610612739
New Orleans Pelicans (NOP): 1610612740
Chicago Bulls (CHI): 1610612741

#### Players

In [3]:
from nba_api.stats.static import players
nba_players = players.get_active_players()
for player in nba_players[:5]:
    print(f"{player['full_name']}: {player['id']}")

Precious Achiuwa: 1630173
Steven Adams: 203500
Bam Adebayo: 1628389
Santi Aldama: 1630583
LaMarcus Aldridge: 200746

#### Team Schedules

In [9]:
from nba_api.stats.endpoints import leaguegamefinder
team_id = "1610612765" # pistons
season = "2021"
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=team_id, season_nullable=season)
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22021,1610612765,DET,Detroit Pistons,1522100066,2021-08-16,DET @ ORL,W,200,79,27,67,0.403,10,35,0.286,15,24,0.625,11,30,41,13,6,5,10,26,1.0
1,22021,1610612765,DET,Detroit Pistons,1522100052,2021-08-14,DET @ LAL,W,201,103,39,81,0.481,14,40,0.350,11,14,0.786,8,32,40,25,12,5,12,17,16.8
2,22021,1610612765,DET,Detroit Pistons,1522100042,2021-08-13,DET vs. NYK,W,200,93,31,72,0.431,18,36,0.500,13,17,0.765,10,39,49,21,2,10,18,20,12.2
3,22021,1610612765,DET,Detroit Pistons,1522100020,2021-08-10,DET @ HOU,L,198,91,33,75,0.440,7,35,0.200,18,26,0.692,10,25,35,14,8,4,16,31,-21.2
4,22021,1610612765,DET,Detroit Pistons,1522100006,2021-08-08,DET vs. OKC,L,201,72,28,71,0.394,7,29,0.241,9,17,0.529,14,35,49,11,9,9,20,23,-7.0

# Endpoints

In [5]:
game_id = "0022100441" # pistons rockets 12/18
player_id = "1628977" # diallo
team_id = "1610612765" # pistons

#### Box Score

In [6]:
from nba_api.stats.endpoints import boxscoretraditionalv2
box_score = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id)

In [7]:
player_stats = box_score.player_stats
player_stats.get_data_frame().head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0022100441,1610612745,HOU,Houston,1630256,Jae'Sean Tate,Jae'Sean,F,,28:15,5.0,10.0,0.500,0.0,2.0,0.000,1.0,2.0,0.5,0.0,5.0,5.0,4.0,3.0,0.0,3.0,4.0,11.0,-1.0
1,0022100441,1610612745,HOU,Houston,1630528,Josh Christopher,Josh,F,,27:46,4.0,6.0,0.667,2.0,3.0,0.667,0.0,0.0,0.0,0.0,4.0,4.0,7.0,1.0,0.0,5.0,1.0,10.0,-3.0
2,0022100441,1610612745,HOU,Houston,1626174,Christian Wood,Christian,C,,30:12,9.0,19.0,0.474,2.0,6.0,0.333,1.0,2.0,0.5,3.0,5.0,8.0,1.0,1.0,1.0,2.0,3.0,21.0,15.0
3,0022100441,1610612745,HOU,Houston,1629726,Garrison Mathews,Garrison,G,,35:45,6.0,12.0,0.500,4.0,9.0,0.444,0.0,0.0,0.0,0.0,5.0,5.0,2.0,3.0,1.0,2.0,1.0,16.0,10.0
4,0022100441,1610612745,HOU,Houston,201569,Eric Gordon,Eric,G,,28:15,7.0,11.0,0.636,3.0,4.0,0.750,1.0,2.0,0.5,0.0,1.0,1.0,5.0,2.0,0.0,2.0,0.0,18.0,5.0

In [8]:
team_stats = box_score.team_stats
team_stats.get_data_frame()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0022100441,1610612745,Rockets,HOU,Houston,240:00,46,93,0.495,14,38,0.368,10,17,0.588,13,34,47,27,15,5,19,18,116,9.0
1,0022100441,1610612765,Pistons,DET,Detroit,240:00,43,93,0.462,10,36,0.278,11,16,0.688,15,27,42,29,8,6,20,24,107,-9.0

Note: There are other box scores including `boxscoreadvancedv2`, `boxscorefourfactorsv2`, `boxscoremiscv2`, `boxscoreplayertrackv2`, `boxscoresummaryv2`, and `boxscoreusagev2`

#### Player Stats by Game

In [93]:
from nba_api.stats.endpoints import playergamelog
player_log = playergamelog.PlayerGameLog(player_id, season="2021")
player_log.get_data_frames()[0].head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22021,1628977,0022100441,"DEC 18, 2021",DET vs. HOU,L,22,3,8,0.375,1,3,0.333,1,3,0.333,0,3,3,0,2,0,1,2,8,-3,1
1,22021,1628977,0022100428,"DEC 16, 2021",DET @ IND,L,25,5,6,0.833,0,0,0.000,2,3,0.667,0,1,1,0,0,0,0,3,12,-2,1
2,22021,1628977,0022100399,"DEC 12, 2021",DET vs. BKN,L,20,5,8,0.625,0,0,0.000,1,2,0.500,1,2,3,1,1,0,1,3,11,-4,1
3,22021,1628977,0022100388,"DEC 10, 2021",DET @ NOP,L,16,4,9,0.444,0,4,0.000,3,3,1.000,2,5,7,2,0,1,0,0,11,-2,1
4,22021,1628977,0022100368,"DEC 08, 2021",DET vs. WAS,L,29,4,7,0.571,2,3,0.667,2,4,0.500,0,2,2,1,1,1,0,5,12,12,1

#### Team Rosters

In [97]:
from nba_api.stats.endpoints import commonteamroster
roster = commonteamroster.CommonTeamRoster(team_id).common_team_roster
roster.get_data_frame().head()

,TeamID,SEASON,LeagueID,PLAYER,NICKNAME,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612765,2021,00,Chris Smith,Chris,chris-smith,0,F,6-9,215,"DEC 24, 1999",21.0,R,UCLA,1630607
1,1610612765,2021,00,Cade Cunningham,Cade,cade-cunningham,2,G,6-6,220,"SEP 25, 2001",20.0,R,Oklahoma State,1630595
2,1610612765,2021,00,Frank Jackson,Frank,frank-jackson,5,G,6-3,205,"MAY 04, 1998",23.0,3,Duke,1628402
3,1610612765,2021,00,Hamidou Diallo,Hamidou,hamidou-diallo,6,G,6-5,202,"JUL 31, 1998",23.0,3,Kentucky,1628977
4,1610612765,2021,00,Killian Hayes,Killian,killian-hayes,7,G,6-5,195,"JUL 27, 2001",20.0,1,Ratiopharm Ulm,1630165

#### Play by Play

In [19]:
# from nba_api.stats.endpoints import playbyplay
# pbp = playbyplay.PlayByPlay("0022100175").play_by_play.get_data_frame()#.head()

# from nba_api.stats.endpoints import playbyplayv2
# pbp2 = playbyplayv2.PlayByPlayV2("0022100175").play_by_play.get_data_frame()#.head()

In [22]:
pbp.EVENTMSGTYPE.value_counts()

4     107
2     103
1      91
8      58
6      31
5      30
3      29
9      11
12      5
13      5
10      3
Name: EVENTMSGTYPE, dtype: int64

In [20]:
pbp.head(30)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
0,0022100175,2,12,0,1,7:46 PM,12:00,None,Start of 1st Period (7:46 PM EST),None,None,None
1,0022100175,4,10,0,1,7:46 PM,12:00,Jump Ball Williams III vs. Portis: Tip to Tatum,None,None,None,None
2,0022100175,7,1,108,1,7:46 PM,11:41,Williams III 2' Cutting Dunk Shot (2 PTS) (Hor...,None,None,0 - 2,2
3,0022100175,9,2,1,1,7:47 PM,11:21,None,None,MISS G. Hill 27' 3PT Jump Shot,None,None
4,0022100175,10,4,0,1,7:47 PM,11:17,None,None,Holiday REBOUND (Off:1 Def:0),None,None
5,0022100175,11,2,80,1,7:47 PM,11:17,None,None,MISS Holiday 26' 3PT Step Back Jump Shot,None,None
6,0022100175,12,4,0,1,7:47 PM,11:16,Williams III REBOUND (Off:0 Def:1),None,None,None,None
7,0022100175,13,2,1,1,7:47 PM,11:06,MISS Horford 12' Jump Shot,None,None,None,None
8,0022100175,14,4,0,1,7:47 PM,11:03,None,None,G. Hill REBOUND (Off:0 Def:1),None,None
9,0022100175,16,1,67,1,7:47 PM,10:51,None,None,Portis 9' Hook Bank Shot (2 PTS) (G. Hill 1 AST),2 - 2,TIE
10,0022100175,18,6,1,1,7:48 PM,10:39,None,None,Connaughton P.FOUL (P1.T1) (N.Green),None,None
11,0022100175,20,2,1,1,7:48 PM,10:26,MISS Schroder 25' 3PT Jump Shot,None,None,None,None
12,0022100175,21,4,0,1,7:48 PM,10:24,Horford REBOUND (Off:1 Def:0),None,None,None,None
13,0022100175,24,1,97,1,7:48 PM,10:24,Horford Tip Layup Shot (2 PTS),None,None,2 - 4,2
14,0022100175,25,1,1,1,7:48 PM,10:02,None,None,Allen 28' 3PT Jump Shot (3 PTS) (Holiday 1 AST),5 - 4,-1
15,0022100175,26,2,57,1,7:49 PM,9:56,MISS Horford 2' Driving Hook Shot,None,None,None,None
16,0022100175,27,4,0,1,7:49 PM,9:54,Horford REBOUND (Off:2 Def:0),None,None,None,None
17,0022100175,28,1,1,1,7:49 PM,9:51,Schroder 25' 3PT Jump Shot (3 PTS) (Horford 2 ...,None,None,5 - 7,2
18,0022100175,30,1,86,1,7:49 PM,9:39,None,None,Portis 8' Turnaround Fadeaway (4 PTS),7 - 7,TIE
19,0022100175,31,2,1,1,7:49 PM,9:29,MISS Horford 3PT Jump Shot,None,None,None,None
20,0022100175,32,4,0,1,7:49 PM,9:27,Williams III REBOUND (Off:1 Def:1),None,None,None,None
21,0022100175,33,2,1,1,7:49 PM,9:25,MISS Schroder 26' 3PT Jump Shot,None,None,None,None
22,0022100175,34,4,0,1,7:49 PM,9:23,Williams III REBOUND (Off:2 Def:1),None,None,None,None
23,0022100175,35,5,2,1,7:49 PM,9:12,Horford Lost Ball Turnover (P1.T1),None,Connaughton STEAL (1 STL),None,None
24,0022100175,37,2,1,1,7:49 PM,9:02,None,None,MISS Holiday 27' 3PT Jump Shot,None,None
25,0022100175,38,4,0,1,7:50 PM,8:58,Tatum REBOUND (Off:0 Def:1),None,None,None,None
26,0022100175,39,1,75,1,7:50 PM,8:51,Tatum 5' Driving Finger Roll Layup (2 PTS),None,None,7 - 9,2
27,0022100175,40,2,1,1,7:50 PM,8:40,None,None,MISS Allen 24' 3PT Jump Shot,None,None
28,0022100175,41,4,0,1,7:50 PM,8:38,Horford REBOUND (Off:2 Def:1),None,None,None,None
29,0022100175,42,1,80,1,7:50 PM,8:29,Tatum 17' Step Back Jump Shot (4 PTS),None,None,7 - 11,4

In [15]:
pbp2

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022100441,2,12,0,1,12:11 PM,12:00,None,Start of 1st Period (12:11 PM EST),None,None,None,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,0
1,0022100441,4,10,0,1,12:11 PM,12:00,,None,None,None,None,4,1630191,Isaiah Stewart,1.610613e+09,Detroit,Pistons,DET,5,1626174,Christian Wood,1.610613e+09,Houston,Rockets,HOU,2,1610612765,None,NaN,None,None,None,1
2,0022100441,7,6,3,1,12:11 PM,11:59,None,None,Wood L.B.FOUL (P1.T1) (K.Cutler),None,None,5,1626174,Christian Wood,1.610613e+09,Houston,Rockets,HOU,4,1630191,Isaiah Stewart,1.610613e+09,Detroit,Pistons,DET,1,0,None,NaN,None,None,None,1
3,0022100441,9,2,98,1,12:11 PM,11:42,MISS Diallo 3' Cutting Layup Shot,None,None,None,None,4,1628977,Hamidou Diallo,1.610613e+09,Detroit,Pistons,DET,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
4,0022100441,10,4,0,1,12:11 PM,11:38,None,None,Tate REBOUND (Off:0 Def:1),None,None,5,1630256,Jae'Sean Tate,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,0022100441,706,2,1,4,2:20 PM,0:06,MISS Cunningham 32' 3PT Jump Shot,None,None,None,None,4,1630595,Cade Cunningham,1.610613e+09,Detroit,Pistons,DET,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
475,0022100441,707,4,0,4,2:20 PM,0:04,Bey REBOUND (Off:1 Def:3),None,None,None,None,4,1630180,Saddiq Bey,1.610613e+09,Detroit,Pistons,DET,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
476,0022100441,708,2,1,4,2:20 PM,0:00,MISS Hayes 26' 3PT Jump Shot,None,None,None,None,4,1630165,Killian Hayes,1.610613e+09,Detroit,Pistons,DET,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
477,0022100441,709,4,0,4,2:20 PM,0:00,None,None,Nwaba REBOUND (Off:2 Def:5),None,None,5,1628021,David Nwaba,1.610613e+09,Houston,Rockets,HOU,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
478,0022100441,710,13,0,4,2:20 PM,0:00,None,End of 4th Period (2:20 PM EST),None,116 - 107,-9,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1